# TODO: Most parameters should be in a default SAC config
name: "sac"

defaults:
  - env_wrappers: []

algorithm:
  _target_: stable_baselines3.SAC
  policy: "MlpPolicy"
  learning_rate: 1e-3
  learning_starts: 100
  tau: 0.005
  gamma: 0.99
  device: "auto"
  train_freq: 4096
  buffer_size: ${train_freq}
  batch_size: 256
  gradient_steps: ${INTDIV:${MUL:10,${train_freq}},${batch_size}} # (10 * train_freq // batch_size)
  action_noise: null
  replay_buffer_class: null
  replay_buffer_kwargs: null
  optimize_memory_usage: False
  ent_coef: "auto"
  target_update_interval: 1
  target_entropy: "auto"
  use_sde: false
  sde_sample_freq: -1
  use_sde_at_warmup: false
  stats_window_size: 100
  policy_kwargs:
    net_arch: [ 256, 256 ]
  verbose: 0
  tensorboard_log: tensorboard

training:
  steps: 500000
  n_envs: 1