# TODO: Most parameters should be in a default SAC config
name: "sac"

defaults:
  - env_wrappers: []

algorithm:
  _target_: stable_baselines3.SAC
  policy: "MlpPolicy"
  learning_rate: 1e-3
  device: "auto"
  train_freq: 4096
  buffer_size: ${train_freq}
  gradient_steps: 40960 # This should be adapted to train_freq (num_epochs * train_freq)
  tensorboard_log: tensorboard

training:
  steps: 500000
  n_envs: 1