# TODO: Most parameters should be in a default SAC config
name: "sac"

defaults:
  - env_wrappers: []

algorithm:
  _target_: stable_baselines3.SAC
  policy: "MlpPolicy"
  learning_rate: 1e-3
  device: ${device}
  tensorboard_log: tensorboard

training:
  steps: 500000
  n_envs: 1