# TODO: Most parameters should be in a default config
name: "td3"

defaults:
  - env_wrappers: []

algorithm:
  _target_: stable_baselines3.TD3
  policy: "MlpPolicy"
  learning_rate: 1e-3
  device: ${device}
  tensorboard_log: tensorboard

training:
  steps: 1000000
  n_envs: 1