[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "action-space-toolbox"
description = ""
version = "0.0.1"
dependencies = [
    "gym==0.21",
    "numpy"
]
authors = [
    {name="Jan Schneider", email="Jan.Schneider@tuebingen.mpg.de"}
]