[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "action_space_toolbox"}

[project]
name = "action-space-toolbox"
description = ""
version = "0.0.1"
authors = [
    {name="Jan Schneider", email="Jan.Schneider@tuebingen.mpg.de"}
]
dependencies = [
    "dm_control",
    "dmc2gym @ git+https://github.com/denisyarats/dmc2gym.git",
    "gym[mujoco]",
    "hydra-core",
    "numpy",
    "omegaconf",
    "Pillow",
    "stable-baselines3",
    "tensorboard",
    "torch"
]

[project.optional-dependencies]
dev = ["pytest"]