defaults:
  - _self_
  - action_transformation: null
  - algorithm: ppo_default

env: Pendulum_TC-v1
env_args: {}
num_parallel_envs: 1
seed: null
show_progress: false

log_dir: ${oc.env:ACTION_SPACE_TOOLBOX_LOG_DIR,logs}
run_log_dir: ${log_dir}/training/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${run_log_dir}
  sweep:
    dir: ${run_log_dir}
  job:
    chdir: true
  verbose: [__main__, action_space_optimization]