defaults:
  - _self_
  - algorithm: ppo_default

env: Pendulum-v1
env_args: {}
seed: null
show_progress: true
num_eval_episodes: 10
eval_interval: 10000
checkpoint_interval: 100_000
save_replay_buffer: false

log_dir: ${oc.env:PG_SUBSPACES_LOG_DIR,logs}
run_log_dir: ${log_dir}/training/${env}/${now:%Y-%m-%d}/${now:%H-%M-%S}

hydra:
  run:
    dir: ${run_log_dir}
  sweep:
    dir: ${run_log_dir}
  job:
    chdir: true
  verbose:
    - __main__