defaults:
  - hess_eigen: hess_eigen_power_method

_target_: rl_subspace_optimization.gradient_subspace.high_curvature_subspace.HighCurvatureSubspace
subspace_dimension: 100
hess_eigen: ???
split_eigenvectors_policy: 0.5