# TODO: Most parameters should be in a default A2C config
name: "a2c"

algorithm:
  _target_: stable_baselines3.A2C
  policy: "MlpPolicy"
  device: "auto"
  tensorboard_log: tensorboard

training:
  steps: 1000000