name: "a2c"

defaults:
  - optimizer: adam

algorithm:
  _target_: stable_baselines3.A2C
  policy: "MlpPolicy"
  device: "auto"
  tensorboard_log: tensorboard
  ent_coef: 0.0
  max_grad_norm: 0.5
  n_steps: 8
  gae_lambda: 0.9
  vf_coef: 0.4
  gamma: 0.99
  use_rms_prop: true
  normalize_advantage: false
  learning_rate:
    _target_: action_space_toolbox.training.schedules.LinearSchedule
    start: 0.00096
    end: 0.0

training:
  steps: 10_000_000
  n_envs: 4