name: "a2c"

defaults:
  - optimizer@algorithm.policy_kwargs.optimizer: adam
  - env_wrappers: []

algorithm:
  _target_: stable_baselines3.A2C
  policy: "MlpPolicy"
  policy_kwargs:
    optimizer: ???
  device: "auto"
  tensorboard_log: tensorboard
  ent_coef: 0.0

training:
  steps: 500_000
  n_envs: 8