# TODO: Most parameters should be in a default config
name: "td3"

defaults:
  - optimizer@algorithm.policy_kwargs.optimizer: adam
  - env_wrappers: []

algorithm:
  _target_: rl_subspace_optimization.parameter_space_exploration.td3_parameter_space_exploration.TD3ParameterSpaceExploration
  policy: "MlpPolicy"
  policy_kwargs:
    optimizer: ???
  learning_rate: 1e-3
  device: "auto"
  tensorboard_log: tensorboard
  exploration_subspace: null
  exploration_parameters_std: 0.001

training:
  steps: 1000000
  n_envs: 1