# TODO: Most parameters should be in a default PPO config
name: "subspace_ppo"

defaults:
  - gradient_subspace@algorithm.gradient_subspace: random_subspace

algorithm:
  _target_: rl_subspace_optimization.subspace_ppo.SubspacePPO
  gradient_subspace: ???
  warmup_steps_orig_space: 10000
  project_before_differentiating: false
  policy: "MlpPolicy"
  device: "auto"
  tensorboard_log: tensorboard

training:
  steps: 1000000
  n_envs: 1
