# TODO: Most parameters should be in a default PPO config
name: "subspace_ppo"

algorithm:
  _target_: rl_subspace_optimization.subspace_ppo.SubspacePPO
  warmup_steps_orig_space: 10000
  gradient_subspace:
    # TODO: This should be a subconfig
    _target_: rl_subspace_optimization.gradient_subspace.random_subspace.RandomSubspace
    subspace_dimension: 100
  policy: "MlpPolicy"
  device: "auto"
  tensorboard_log: tensorboard

training:
  steps: 1000000
  n_envs: 1