_target_: action_space_toolbox.analysis.cliff_analysis.cliff_analysis.CliffAnalysis
analysis_run_id: default
num_processes: 1
num_samples_true_gradient: 1_000_000
num_trials: 10
num_episodes_reward_eval: 1_000
num_env_steps_training: 2048
cliff_test_distance: 0.02     # TODO: Check that the original code actually uses 0.02 (as opposed to the paper, which says 0.04)
alternate_agent_cfg: null
algorithm_overrides:
  ppo:
    - learning_rate: 0.0001
      n_steps: 128
    - learning_rate: 0.01
      n_steps: 128
    - learning_rate: 0.5
      n_steps: 128
    - learning_rate: 0.0001
      n_steps: 2048
    - learning_rate: 0.01
      n_steps: 2048
    - learning_rate: 0.5
      n_steps: 2048
  a2c:
    - learning_rate: 0.0001
      n_steps: 128
    - learning_rate: 0.01
      n_steps: 128
    - learning_rate: 0.5
      n_steps: 128
    - learning_rate: 0.0001
      n_steps: 2048
    - learning_rate: 0.01
      n_steps: 2048
    - learning_rate: 0.5
      n_steps: 2048