_target_: action_space_toolbox.analysis.reward_surface_visualization.reward_surface_visualization.RewardSurfaceVisualization
analysis_run_id: default
grid_size: 31
magnitude: 1.0
plot_in_gradient_direction: false
num_samples_true_gradient: 1_000_000
num_steps: 200_000
num_plots: 1
num_processes: 1
plot_sgd_steps: true
plot_true_gradient_steps: true
max_gradient_trajectories: 10
max_steps_per_gradient_trajectory: null