_target_: action_space_toolbox.analysis.reward_surface_visualization.reward_surface_visualization.RewardSurfaceVisualization
grid_size: 31
magnitude: 1.0
num_steps: 200000
num_plots: 1
num_processes: 1