defaults:
  - hessian_eigen: lanczos

_target_: action_space_toolbox.analysis.reward_surface_visualization.reward_surface_visualization.RewardSurfaceVisualization
analysis_run_id: default
grid_size: 31
magnitude: 1.0
direction_types: [rand, rand]
fix_rand_dirs_at_checkpoint: false
num_samples_true_loss: 1_000_000
num_steps: 200_000
num_plots: 1
num_processes: 1
plot_sgd_steps: true
plot_true_gradient_steps: true
max_gradient_trajectories: 10
max_steps_per_gradient_trajectory: null
hessian_eigen: ???