_target_: rl_subspace_optimization.optimizer.diagonal_bias_sgd.DiagonalBiasSGD
momentum: 0.0
dampening: 0.0
weight_decay: 0.0
nesterov: False
maximize: false
foreach: null
differentiable: false
bias_parameter: 0.0