_target_: rl_subspace_optimization.optimizer.rotation_invariant_adam.RotationInvariantAdam
betas:
  - 0.9
  - 0.999
eps: 1e-5
weight_decay: 0
amsgrad: false
foreach: null
maximize: false
capturable: false
